Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 526, in build_workflow
    layout, participant_label=opts.participant_label)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/utils/bids.py", line 107, in collect_participants
    ', '.join(participant_label)), bids_dir)
niworkflows.utils.bids.BIDSError: 
---------- BIDS root folder: "BIDS Layout: ...dapt_lab/shared/TPOT/bids_data | Subjects: 156 | Sessions: 156 | Runs: 317" ----------
           Could not find participants [TPOT051_2]
------------------------------------------------------------------------------------------------------------------------------------
